"""Added messaging service, deleted phone number

Revision ID: 0f9774ae4896
Revises: 139742411c46
Create Date: 2020-06-03 15:36:45.410664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f9774ae4896'
down_revision = '139742411c46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('message_service_sid', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'customer', ['email_address'])
    op.drop_column('customer', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'customer', type_='unique')
    op.drop_column('customer', 'message_service_sid')
    # ### end Alembic commands ###
