"""empty message

Revision ID: 139742411c46
Revises: b661b4bc86f9
Create Date: 2019-07-11 10:40:34.991230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139742411c46'
down_revision = 'b661b4bc86f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('city', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('post_code', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('street_address', sa.String(), nullable=True))
    op.drop_column('customer', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'street_address')
    op.drop_column('customer', 'post_code')
    op.drop_column('customer', 'city')
    # ### end Alembic commands ###
