"""id to id_

Revision ID: 47f97ad93700
Revises: 810b24a862a7
Create Date: 2020-06-05 22:18:29.953678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f97ad93700'
down_revision = '810b24a862a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subaccount_user', sa.Column('id_', sa.Integer(), nullable=False))
    op.drop_column('subaccount_user', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subaccount_user', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('subaccount_user', 'id_')
    # ### end Alembic commands ###
