"""removed unique check on email. Not really necessary for demo

Revision ID: 4a00ac61fcda
Revises: 0f9774ae4896
Create Date: 2020-06-03 15:48:39.875597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a00ac61fcda'
down_revision = '0f9774ae4896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customer_email_address_key', 'customer', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('customer_email_address_key', 'customer', ['email_address'])
    # ### end Alembic commands ###
