"""retry int to str

Revision ID: 73d95926a815
Revises: 47f97ad93700
Create Date: 2020-06-05 22:41:03.350245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d95926a815'
down_revision = '47f97ad93700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subaccount_user', 'id_',
               existing_type=sa.INTEGER(),
               type_=sa.String())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subaccount_user', 'id_',
               existing_type=sa.String(),
               type_=sa.INTEGER())
    # ### end Alembic commands ###
