"""added user table to handle Google Login

Revision ID: 810b24a862a7
Revises: aeb1ec2aea09
Create Date: 2020-06-05 10:40:13.971235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810b24a862a7'
down_revision = 'aeb1ec2aea09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subaccount_customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('street_address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('post_code', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('twilio_account_sid', sa.String(), nullable=True),
    sa.Column('twilio_auth_token', sa.String(), nullable=True),
    sa.Column('message_service_sid', sa.String(), nullable=True),
    sa.Column('sendgrid_account_sid', sa.String(), nullable=True),
    sa.Column('sendgrid_auth_token', sa.String(), nullable=True),
    sa.Column('sendgrid_from_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subaccount_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('twilio_account_sid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('twilio_auth_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sendgrid_account_sid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sendgrid_auth_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sendgrid_from_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('post_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('street_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message_service_sid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='customer_pkey')
    )
    op.drop_table('subaccount_user')
    op.drop_table('subaccount_customer')
    # ### end Alembic commands ###
