"""missing column pic

Revision ID: a62f51d63cc8
Revises: 73d95926a815
Create Date: 2020-06-05 22:46:11.803042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a62f51d63cc8'
down_revision = '73d95926a815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subaccount_user', sa.Column('profile_pic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subaccount_user', 'profile_pic')
    # ### end Alembic commands ###
