"""messed up phone number column

Revision ID: aeb1ec2aea09
Revises: 4a00ac61fcda
Create Date: 2020-06-04 19:54:49.384833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb1ec2aea09'
down_revision = '4a00ac61fcda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone_number', sa.String(), nullable=True))
    op.drop_column('customer', 'twilio_phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('twilio_phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'phone_number')
    # ### end Alembic commands ###
