"""empty message

Revision ID: b661b4bc86f9
Revises: 
Create Date: 2019-07-10 16:05:36.550539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b661b4bc86f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('twilio_account_sid', sa.String(), nullable=True),
    sa.Column('twilio_auth_token', sa.String(), nullable=True),
    sa.Column('twilio_phone_number', sa.String(), nullable=True),
    sa.Column('sendgrid_account_sid', sa.String(), nullable=True),
    sa.Column('sendgrid_auth_token', sa.String(), nullable=True),
    sa.Column('sendgrid_from_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    # ### end Alembic commands ###
